Fix/single response
OneSignal/OneSignal-Flutter-SDK pull request #445
Opened 2021-07-27 15:49 UTC by Jeasmine

Add single response handler 

* Some calls might end being called twice from the native side. Even if we already cover this from the native side, add safe
check to avoid more than one call to the same flutter response

2021-07-28 18:25 UTC, jkasten2 requested changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/445)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @emawby, @Jeasmine, @nan-li, and @tanaynigam)

___
*[android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java, line 161 at r1](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/445#-MfiKB4J65r148XV1t7D:-MfiKB4K9M8zwDFF2uOx:b-39e0ym) ([raw file](https://github.com/onesignal/onesignal-flutter-sdk/blob/9e7be53ab6c61cab6c7de80a20c2c1e7a506fade/android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java#L161)):*
> ```Java
> 
>   private void addObservers() {
>     // Clean observers before setting, avoid being call twice
> ```

These are already in main. Looks like this branch is branched from `fix/sms-userid-number`, so once that is merged in this diff will probably be fixed.
___
*[android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java, line 390 at r1](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/445#-MfiLj3u243E8pVR1ckD:-MfiLj3u243E8pVR1ckE:b13ebvj) ([raw file](https://github.com/onesignal/onesignal-flutter-sdk/blob/9e7be53ab6c61cab6c7de80a20c2c1e7a506fade/android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java#L390)):*
> ```Java
> 
>   static class OSFlutterEmailHandle extends FlutterRegistrarResponder
>           implements OneSignal.EmailUpdateHandler {
> ```

Why do we have `OSFlutterEmailHandle` and then `OSFlutterResultHandler` for all the other callbacks? This is inconsistent, they should either all be their own class or all under the same one.
___
*[android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java, line 405 at r1](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/445#-MfiL4E_8CuWFdHf7mWK:-MfiL4E_8CuWFdHf7mWL:b-40iucl) ([raw file](https://github.com/onesignal/onesignal-flutter-sdk/blob/9e7be53ab6c61cab6c7de80a20c2c1e7a506fade/android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java#L405)):*
> ```Java
>     public void onSuccess() {
>       if (this.replySubmitted.getAndSet(true))
>           return;
> ```

Can we also print a warning to the logcat if this happens? This way we have it if we need to debug in the future.


<!-- Sent from Reviewable.io -->

2021-08-05 18:56 UTC, emawby requested changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/445)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @emawby, @Jeasmine, @jkasten2, @nan-li, and @tanaynigam)

___
*[android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java, line 402 at r2](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/445#-MgMevt2A3WWDtvBtQXa:-MgMevt2A3WWDtvBtQXb:b-6ot9ic) ([raw file](https://github.com/onesignal/onesignal-flutter-sdk/blob/c7c4722732b68d3875f30b12eff92b05e04560be/android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java#L402)):*
> ```Java
>           implements OneSignal.EmailUpdateHandler {
> 
>     OSFlutterEmailHandle(PluginRegistry.Registrar flutterRegistrar, MethodChannel channel, Result res, String methodName) {
> ```

Typo in the name. This should be OSFlutterEmailHandler 


<!-- Sent from Reviewable.io -->

2021-08-05 19:39 UTC, jkasten2 approved these changes
This PR will cover the issue so approving. We Probably want to try find a better balance with code reuse where possible but still have consistency for the future with these callbacks.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/445#-:-MgMoLNFAWo1s3IwqXPe:b-8dk7f5)* status: all files reviewed, 4 unresolved discussions (waiting on @Jeasmine, @jkasten2, @nan-li, and @tanaynigam)



<!-- Sent from Reviewable.io -->

2021-08-05 20:07 UTC, jkasten2 approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/445)* status: all files reviewed, 3 unresolved discussions (waiting on @Jeasmine, @jkasten2, @nan-li, and @tanaynigam)



<!-- Sent from Reviewable.io -->

2021-08-05 20:08 UTC, merged