Android plugin API updated to support v2 Embedding
OneSignal/OneSignal-Flutter-SDK pull request #486
Opened 2021-09-14 18:41 UTC by luis901101

As requested here [Issue 480](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/480), it's necessary to update the Android implementation to support the v2 Embedding which it's the default for new Android plugins and it is highly recommended to be update it because future release of Flutter will fail to build with deprecated Android embedding.
I migrated the Android implementation to support embedding v2 while remaining compatible with apps that don’t use the v2 Android embedding.

2021-09-28 16:57 UTC, danielgomezrico commented
@Jeasmine any chance to check this?

2021-10-04 15:54 UTC, charlesarchibong commented
@emawby please can you review

2021-10-04 16:59 UTC, emawby requested changes
> Reviewed 1 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/486)* status: 1 of 23 files reviewed, 4 unresolved discussions (waiting on @emawby and @luis901101)

*[a discussion](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/486#-MlBESoyA8ncNTMiS9Zo:-MlBESoyA8ncNTMiS9Zp:b-nyfp18) (no related file):*
Thank you so much for the contribution this looks great! I would like to clean this PR up to only the required changes if possible. There are a lot of changes to files in .idea and gradle versions. Are all of those changes necessary? 

---
___
*[.idea/modules.xml, line 5 at r1](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/486#-MlBDkbm4QcRqVpto2FV:-MlBDkbnC1Trj1ut7DXH:b-lpfcld) ([raw file](https://github.com/onesignal/onesignal-flutter-sdk/blob/8d2013eb05a5779a3e19d4bb20dd16a8d5aa90b7/.idea/modules.xml#L5)):*
> ```XML
>   <component name="ProjectModuleManager">
>     <modules>
>       <module fileurl="file://$PROJECT_DIR$/.idea/onesignal_flutter_official_fork.iml" filepath="$PROJECT_DIR$/.idea/onesignal_flutter_official_fork.iml" />
> ```

I don't think we want to commit this change to the main branch
___
*[android/build.gradle, line 11 at r1](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/486#-MlBEGltA_lAjC84IZ8N:-MlBEGluC6u_N377XNuI:b-zaqmrt) ([raw file](https://github.com/onesignal/onesignal-flutter-sdk/blob/8d2013eb05a5779a3e19d4bb20dd16a8d5aa90b7/android/build.gradle#L11)):*
> ```Gradle
> 
>     dependencies {
>         classpath 'com.android.tools.build:gradle:3.5.3'
> ```

Is this gradle version bump required for these changes?
___
*[android/gradle/wrapper/gradle-wrapper.properties, line 6 at r1](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/486#-MlBELLB6cZotGUQ7dAY:-MlBELLB6cZotGUQ7dAZ:b-nw0074) ([raw file](https://github.com/onesignal/onesignal-flutter-sdk/blob/8d2013eb05a5779a3e19d4bb20dd16a8d5aa90b7/android/gradle/wrapper/gradle-wrapper.properties#L6)):*
> ```INI
> zipStoreBase=GRADLE_USER_HOME
> zipStorePath=wrapper/dists
> distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip
> ```

Is this gradle version change required?


<!-- Sent from Reviewable.io -->

2021-10-04 17:04 UTC, luis901101 commented
Nop, those changes you ask are not required at all.

2021-10-04 21:33 UTC, jkasten2 requested changes
@luis901101 Appreciate the contribution here! I reviewed your PR as well and the changes to the logic to support the Flutter V2 Android API themselves look good. However as @emawby noted there are unrelated changes to project files, some not compatible with `main`.

@luis901101 If you can address those comments and remove any changes you know are not necessary we can merge this PR in. If your not in a good position to make these changes this week let us know and we can make the needed changes.

2021-10-04 21:37 UTC, luis901101 commented
Ok, I'll remove those changes

2021-10-05 03:54 UTC, jkasten2 approved these changes
Thanks for the clean up, looks good to me!
@emawby If you want to take another quick pass at the comments you left and approve one of us can merge it in.

2021-10-05 17:49 UTC, danielgomezrico commented
@luis901101 after some change that you pushed we get a failure getting the dependency from github:

```
Could not find a file named "pubspec.yaml" in https://github.com/luis901101/OneSignal-Flutter-SDK.git 8d2013eb05a5779a3e19d4bb20dd16a8d5aa90b7.
```

It looks like that commit that we were referencing does not exist anymore, maybe you changed the history somehow?

2021-10-05 18:03 UTC, luis901101 commented
> @luis901101 after some change that you pushed we get a failure getting the dependency from github:
> 
> ```
> Could not find a file named "pubspec.yaml" in https://github.com/luis901101/OneSignal-Flutter-SDK.git 8d2013eb05a5779a3e19d4bb20dd16a8d5aa90b7.
> ```
> 
> It looks like that commit that we were referencing does not exist anymore, maybe you changed the history somehow?

Yep after I removed unnecessary file changes from PR yesterday that commit is not available any more, the commit now is `952e78c1c6f7ace65082914f4e90f6667b6b382c`... but I don't understand why you get that error... are you referencing that commit directly in your pubpsec depedencies ? If that's the case I recommend you to reference the branch like this:

```yaml
onesignal_flutter: #^3.2.3
    git:
      url: https://github.com/luis901101/OneSignal-Flutter-SDK.git
      ref: migrate_android_embedding_v2
```
That way does not matter the commit, it will download the latest commit to that branch which is the one I did yesterday.

2021-10-05 18:29 UTC, merged

2021-10-05 19:29 UTC, danielgomezrico commented
@luis901101 yeah, when you do a `pub get` it reference a commit in the `pubspec.lock`.

It's awesome that the PR was merged!

2021-10-05 19:37 UTC, jesselpereira commented
Great PR @luis901101, congrats for your efforts.