Add in app mesage lifecycle handler
OneSignal/OneSignal-Flutter-SDK pull request #531
Opened 2022-01-21 21:38 UTC by tanaynigam

## Description
## Line Summary
Adds the In-App Message Lifecycle Handler which includes up to 4 callbacks for the displaying and dismissing of In-App Messages.

## Details
### Motivation
This handler was added to give customers visibility into the display lifecycle of IAMs: when an IAM will be displayed, and also when it has been dismissed.

### Scope
Extra fields will show up if a user logs the OSInAppMessage instead of just its messageId property, which is fine.
In-App Messages are only read and not modified.

### Public API Changes
The documentation will need to be updated for react native to provide these new methods.
* Add `onWillDisplayInAppMessage`, `onDidDisplayInAppMessage`, `onWillDismissInAppMessage`, `onDidDismissInAppMessage` handlers to Android and iOS
* Add respective handlers to OneSignal dart file
* Add example handlers to the example app

## Testing
### Manual Testing
* Test device using IAM lifecycle handlers on Android and iOS. The IAM lifecycle handlers trigger on receiving an In-app message.

2022-01-25 18:14 UTC, emawby requested changes
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/531)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @jkasten2, @nan-li, and @tanaynigam)

___
*[android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java, line 174 at r1](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/531#-MuHQPfpAEn3QS-5xCUT:-MuHQPfpAEn3QS-5xCUU:b-cxo7y4) ([raw file](https://github.com/onesignal/onesignal-flutter-sdk/blob/f4aeb6eb67031d20f68bece322185bc30bfe550b/android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java#L174)):*
> ```Java
>       this.OnWillDisplayInAppMessageHandlerParams();
>     else if (call.method.contentEquals("OneSignal#onDidDisplayInAppMessageHandlerParams"))
>       this.OnWillDisplayInAppMessageHandlerParams();  
> ```

this is calling OnWillDisplat instead of onDidDisplay
___
*[android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java, line 176 at r1](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/531#-MuHQU1o6erLPMUyTCa6:-MuHQU1o6erLPMUyTCa7:bele0le) ([raw file](https://github.com/onesignal/onesignal-flutter-sdk/blob/f4aeb6eb67031d20f68bece322185bc30bfe550b/android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java#L176)):*
> ```Java
>       this.OnWillDisplayInAppMessageHandlerParams();  
>     else if (call.method.contentEquals("OneSignal#onWillDismissInAppMessageHandlerParams"))
>       this.OnWillDisplayInAppMessageHandlerParams();  
> ```

willdisplay instead of willdismiss
___
*[android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java, line 178 at r1](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/531#-MuHQWHV8Uud2e6nwx1C:-MuHQWHW-r4XcmS0ov0Q:b-3q5b1b) ([raw file](https://github.com/onesignal/onesignal-flutter-sdk/blob/f4aeb6eb67031d20f68bece322185bc30bfe550b/android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java#L178)):*
> ```Java
>       this.OnWillDisplayInAppMessageHandlerParams();  
>     else if (call.method.contentEquals("OneSignal#onDidDismissInAppMessageHandlerParams"))
>       this.OnWillDisplayInAppMessageHandlerParams();  
> ```

willdisplay instead of diddismiss


<!-- Sent from Reviewable.io -->

2022-02-01 18:01 UTC, emawby approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/531)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @emawby, @jkasten2, and @nan-li)



<!-- Sent from Reviewable.io -->

2022-02-01 21:04 UTC, nan-li approved these changes
I tried this out on Android and LGTM

2022-02-03 00:06 UTC, jkasten2 requested changes
I have main point comment around removing code that is trying to handle missed events. See details on the specific lines below.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/531#-:-MuwtcR2D8fvIit8a2UQ:bko7syb)* status: all files reviewed, 3 unresolved discussions (waiting on @tanaynigam)

___
*[android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java, line 62 at r2](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/531#-MuwrVUz73xDo3OUoQF6:-MuwrVUz73xDo3OUoQF7:bk673vj) ([raw file](https://github.com/onesignal/onesignal-flutter-sdk/blob/68b8e362eee5e41b3e929468fed166a2d1c0b398/android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java#L62)):*
> ```Java
>   private boolean waitingForUserPrivacyConsent = false;
> 
>   private OSInAppMessage inAppMessage;
> ```

I see this variable is to store the last IAM that had one of these newly added display / dismiss events. It is then read and reset if we added a new handler so it can fire a missed event if the handler was setup late. However it the way it is setup now it will only fire one event instead of all of them. The biggest thing is though these are more real time events where knowing about these after that fact would not be every useful.

Given the above I believe we not include the variable and this logic using it below.
___
*[android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java, line 466 at r2](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/531#-MuwsihGCfb0UV5kr1yw:-MuwsihGCfb0UV5kr1yx:bgy7j4i) ([raw file](https://github.com/onesignal/onesignal-flutter-sdk/blob/68b8e362eee5e41b3e929468fed166a2d1c0b398/android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java#L466)):*
> ```Java
>         @Override
>         public void onWillDisplayInAppMessage(OSInAppMessage message) { 
>           onWillDisplayInAppMessageFlutter(message);
> ```

Given my comment above where `inAppMessage` is defined we can simplify this to do the `this.hasSetOnWillDisplayInAppMessageHandler` if check and call `invokeMethodOnUiThread("OneSignal#onWillDisplayInAppMessage"` directly here to.

Same goes for the 3 other methods below. And same for iOS as well.
___
*[ios/Classes/OneSignalPlugin.m, line 64 at r2](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/531#-MuwtTrw-sGtD1MUGtHm:-MuwtTrw-sGtD1MUGtHn:bl1fcq5) ([raw file](https://github.com/onesignal/onesignal-flutter-sdk/blob/68b8e362eee5e41b3e929468fed166a2d1c0b398/ios/Classes/OneSignalPlugin.m#L64)):*
> ```objc
> @property (atomic) BOOL hasSetOnDidDismissInAppMessageHandler;
> 
> @property (strong, nonatomic) OSInAppMessage *inAppMessage;
> ```

Apply the same to iOS as my Android comment above.


<!-- Sent from Reviewable.io -->

2022-02-22 23:41 UTC, jkasten2 approved these changes
@tanaynigam PR looks good, just one nit on removing and extra unused variable. Feel free to merge without another approval after fixing.

> Reviewed 7 of 10 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/531#-:-MwYnkK79g4adjm9V1LC:b-i3yzd)* status: all files reviewed, 3 unresolved discussions (waiting on @tanaynigam)

___
*[android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java, line 62 at r2](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/531#-MuwrVUz73xDo3OUoQF6:-MwYZiZm8gIf5tV3eAY3:bwrvhuk) ([raw file](https://github.com/onesignal/onesignal-flutter-sdk/blob/68b8e362eee5e41b3e929468fed166a2d1c0b398/android/src/main/java/com/onesignal/flutter/OneSignalPlugin.java#L62)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

I see this variable is to store the last IAM that had one of these newly added display / dismiss events. It is then read and reset if we added a new handler so it can fire a missed event if the handler was setup late. However it the way it is setup now it will only fire one event instead of all of them. The biggest thing is though these are more real time events where knowing about these after that fact would not be every useful.

Given the above I believe we not include the variable and this logic using it below.
</blockquote></details>

All logic that was using this instanced `inAppMessage`has been removed, however removal of this var was missed.


<!-- Sent from Reviewable.io -->

2022-02-24 18:30 UTC, jkasten2 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-flutter-sdk/531#-:-MwgzzQ373Lx7SW3V2PO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @tanaynigam)



<!-- Sent from Reviewable.io -->

2022-02-25 00:45 UTC, merged